### ISSUE TITLE
Not working with Mac OS

### ISSUE THREAD

**Issue by kellyvv** [Upsonic/Upsonic#10]

**Comment by onuratakan** [comment]
Hi, can you share a screen shot. Actualy i know there is some problems caused by pyqt5 but it can be fixed.

**Comment by kellyvv** [comment]
<img width="888" alt="image" src="https://github.com/onuratakan/gpt-computer-assistant/assets/129767595/eb1a9c73-8941-40d9-ba14-f550700dfbd0">

**Comment by onuratakan** [comment]
@kellyzxiaowei I just made fix. Can you try again.

**Comment by kellyvv** [comment]
> @kellyzxiaowei I just made fix. Can you try again.

(venv) zxw@VdeMacBook-Pro gpt-computer-assistant % computerassistant
Profile: None
[02:14:06] Upsonic active                                                                      on_prem.py:130
Error: Remote is down
Traceback (most recent call last):
  File "/Users/zxw/AITOOL/gpt-computer-assistant/venv/lib/python3.11/site-packages/upsonic/remote/on_prem.py", line 1422, in langchain
    the_tool = tool(the_function)
               ^^^^^^^^^^^^^^^^^^
  File "/Users/zxw/AITOOL/gpt-computer-assistant/venv/lib/python3.11/site-packages/langchain_core/tools.py", line 960, in tool
    return _make_with_name(args[0].__name__)(args[0])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zxw/AITOOL/gpt-computer-assistant/venv/lib/python3.11/site-packages/langchain_core/tools.py", line 925, in _make_tool
    return StructuredTool.from_function(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zxw/AITOOL/gpt-computer-assistant/venv/lib/python3.11/site-packages/langchain_core/tools.py", line 836, in from_function
    description_ = textwrap.dedent(description_).strip()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.9/Frameworks/Python.framework/Versions/3.11/lib/python3.11/textwrap.py", line 435, in dedent
    text = _whitespace_only_re.sub('', text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'list'

Traceback (most recent call last):
  File "/Users/zxw/AITOOL/gpt-computer-assistant/venv/bin/computerassistant", line 8, in <module>
    sys.exit(start())
             ^^^^^^^
  File "/Users/zxw/AITOOL/gpt-computer-assistant/venv/lib/python3.11/site-packages/gpt_computer_assistant/start.py", line 19, in start
    from .gpt_computer_assistant import QApplication, MainWindow, sys
  File "/Users/zxw/AITOOL/gpt-computer-assistant/venv/lib/python3.11/site-packages/gpt_computer_assistant/gpt_computer_assistant.py", line 1, in <module>
    from .agent.chat_history import *
  File "/Users/zxw/AITOOL/gpt-computer-assistant/venv/lib/python3.11/site-packages/gpt_computer_assistant/agent/__init__.py", line 2, in <module>
    from .assistant import *
  File "/Users/zxw/AITOOL/gpt-computer-assistant/venv/lib/python3.11/site-packages/gpt_computer_assistant/agent/assistant.py", line 5, in <module>
    from ..screen.shot import *
  File "/Users/zxw/AITOOL/gpt-computer-assistant/venv/lib/python3.11/site-packages/gpt_computer_assistant/screen/shot.py", line 3, in <module>
    import pyautogui
  File "/Users/zxw/AITOOL/gpt-computer-assistant/venv/lib/python3.11/site-packages/pyautogui/__init__.py", line 246, in <module>
    import mouseinfo
  File "/Users/zxw/AITOOL/gpt-computer-assistant/venv/lib/python3.11/site-packages/mouseinfo/__init__.py", line 100, in <module>
    from rubicon.objc import ObjCClass, CGPoint
  File "/Users/zxw/AITOOL/gpt-computer-assistant/venv/lib/python3.11/site-packages/rubicon/objc/__init__.py", line 33, in <module>
    from . import api, collections, runtime, types
  File "/Users/zxw/AITOOL/gpt-computer-assistant/venv/lib/python3.11/site-packages/rubicon/objc/api.py", line 29, in <module>
    from .runtime import (
  File "/Users/zxw/AITOOL/gpt-computer-assistant/venv/lib/python3.11/site-packages/rubicon/objc/runtime.py", line 460, in <module>
    libobjc.objc_msgSendSuper_stret.restype = None
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.9/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ctypes/__init__.py", line 389, in __getattr__
    func = self.__getitem__(name)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.9/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ctypes/__init__.py", line 394, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: dlsym(0x31a437110, objc_msgSendSuper_stret): symbol not found

Can not working.

**Comment by onuratakan** [comment]
Hi are you working with intel macos?

**Comment by HarbingerOfFire** [comment]
Looking at it, it seems to fail when importing Rubicon objective-C for PyAutoGUI. The code it is failing on is architecture specific, and it only works on 32-bit or ARM processors. You can check the architecture in the place shown below. 
![image](https://github.com/onuratakan/gpt-computer-assistant/assets/154275077/ec5f9e18-3951-4508-8aac-4b0f811b90b9)
Apple M1 and M2 work well, and so do intel x86. However, if you have an intel x64, this is likely an error with rubicon not correctly identifying architecture.

**Comment by onuratakan** [comment]
> Looking at it, it seems to fail when importing Rubicon objective-C for PyAutoGUI. The code it is failing on is architecture specific, and it only works on 32-bit or ARM processors. You can check the architecture in the place shown below. 
> ![image](https://github.com/onuratakan/gpt-computer-assistant/assets/154275077/ec5f9e18-3951-4508-8aac-4b0f811b90b9)
> Apple M1 and M2 work well, and so do intel x86. However, if you have an intel x64, this is likely an error with rubicon not correctly identifying architecture.

Oh thanks for detailed explaination. Do you know any solution for this or writing another gui for intel macos?

**Comment by HarbingerOfFire** [comment]
I would say the only alternative I know is to replace the use of pyautogui for mac environments with an Objective-C bridge and do things manually. There may be a little bit of a learning curve, but I suggest pyobjc because it is native to MacOS, and can be used to do much of the same things when paired with Quartz.

**Comment by gokborayilmaz** [comment]
Okey, we will work on it.
