### ISSUE TITLE
TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'   

### ISSUE THREAD

**Issue by Liya020** [Upsonic/Upsonic#116]
Hi, I am using python 3.12.4. After installing the gpt computer assistant in command, I failed to run it in command, it shows below codes:

C:\Users\90471>computerassistant
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\Program Files\PYTHON\Scripts\computerassistant.exe\__main__.py", line 4, in <module>
  File "D:\Program Files\PYTHON\Lib\site-packages\gpt_computer_assistant\__init__.py", line 5, in <module>
    from .tooler import Tool
  File "D:\Program Files\PYTHON\Lib\site-packages\gpt_computer_assistant\tooler.py", line 1, in <module>
    from langchain.tools import tool
  File "D:\Program Files\PYTHON\Lib\site-packages\langchain\tools\__init__.py", line 23, in <module>
    from langchain_core.tools import BaseTool, StructuredTool, Tool, tool
  File "D:\Program Files\PYTHON\Lib\site-packages\langchain_core\tools.py", line 34, in <module>
    from langchain_core.callbacks import (
  File "D:\Program Files\PYTHON\Lib\site-packages\langchain_core\callbacks\__init__.py", line 22, in <module>
    from langchain_core.callbacks.manager import (
  File "D:\Program Files\PYTHON\Lib\site-packages\langchain_core\callbacks\manager.py", line 29, in <module>
    from langsmith.run_helpers import get_run_tree_context
  File "D:\Program Files\PYTHON\Lib\site-packages\langsmith\run_helpers.py", line 40, in <module>
    from langsmith import client as ls_client
  File "D:\Program Files\PYTHON\Lib\site-packages\langsmith\client.py", line 52, in <module>
    from langsmith import env as ls_env
  File "D:\Program Files\PYTHON\Lib\site-packages\langsmith\env\__init__.py", line 3, in <module>
    from langsmith.env._runtime_env import (
  File "D:\Program Files\PYTHON\Lib\site-packages\langsmith\env\_runtime_env.py", line 10, in <module>
    from langsmith.utils import get_docker_compose_command
  File "D:\Program Files\PYTHON\Lib\site-packages\langsmith\utils.py", line 31, in <module>
    from langsmith import schemas as ls_schemas
  File "D:\Program Files\PYTHON\Lib\site-packages\langsmith\schemas.py", line 69, in <module>
    class Example(ExampleBase):
  File "D:\Program Files\PYTHON\Lib\site-packages\pydantic\v1\main.py", line 286, in __new__
    cls.__try_update_forward_refs__()
  **File "D:\Program Files\PYTHON\Lib\site-packages\pydantic\v1\main.py", line 807, in __try_update_forward_refs__
    update_model_forward_refs(cls, cls.__fields__.values(), cls.__config__.json_encoders, localns, (**NameError,))****
  File "D:\Program Files\PYTHON\Lib\site-packages\pydantic\v1\typing.py", line 554, in update_model_forward_refs
    update_field_forward_refs(f, globalns=globalns, localns=localns)
  File "D:\Program Files\PYTHON\Lib\site-packages\pydantic\v1\typing.py", line 520, in update_field_forward_refs
    field.type_ = evaluate_forwardref(field.type_, globalns, localns or None)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\PYTHON\Lib\site-packages\pydantic\v1\typing.py", line 66, in evaluate_forwardref
    return cast(Any, type_)._evaluate(globalns, localns, set())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
**TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'**

 I'm not good at coding. Can anyone help? Thanks.

**Comment by Abhinavcode13** [comment]
```
pip3 install gpt-computer-assistant
```
Did you run the above command prior to running `computerassistant` ?

**Comment by Liya020** [comment]
> ```
> pip3 install gpt-computer-assistant
> ```
> 
> Did you run the above command prior to running `computerassistant` ?

Yes, I did. It downloaded a lot of files, and looks like the installation succeeded. Then I try to run it and failed.

**Comment by Mideky-hub** [comment]
What if you :
- Go to the root directory
- type in the cmd "pip3 install -r requirements.txt"

**Comment by erquier** [comment]
Im having the same issue I even tryed to run the: "pip3 install -r requirements.txt"

**Comment by staneychan** [comment]
I have the same problem with python 3.12.4
And it works fine after replaced with python 3.12.3

**Comment by Mideky-hub** [comment]
@erquier Try then reverting the Python version as @staneychan and if this still doesn't work : 
- pipx install cookiecutter
- pipx runpip cookicutter install -r requirements.txt

**Comment by mustafadakhel** [comment]
I'm facing the same issue, i was using python 3.12.4 and downgrading to 3.12.3 fixed it for me

**Comment by onuratakan** [comment]
> I have the same problem with python 3.12.4 And it works fine after replaced with python 3.12.3
> I'm facing the same issue, i was using python 3.12.4 and downgrading to 3.12.3 fixed it for me

Ouu its so interesting, ı should put an information about it. And working for fixing. Thank you so much.

**Comment by Jerry-Terrasse** [comment]
Update pydantic to 2.7.4 will solve the problem. https://github.com/langchain-ai/langchain/issues/22692#issuecomment-2164354344
