### ISSUE TITLE
Xlib.error.DisplayConnectionError: Can't connect to display ":0": b'Authorization required, but no authorization protocol specified\n'

### ISSUE THREAD

**Issue by bukhanka** [Upsonic/Upsonic#123]
Eror:
Traceback (most recent call last):
  File "/home/dukhanin/venvs/gpt-computer-assistant/bin/computerassistant", line 5, in <module>
    from gpt_computer_assistant.start import start
  File "/home/dukhanin/venvs/gpt-computer-assistant/lib/python3.12/site-packages/gpt_computer_assistant/__init__.py", line 5, in <module>
    from .tooler import Tool
  File "/home/dukhanin/venvs/gpt-computer-assistant/lib/python3.12/site-packages/gpt_computer_assistant/tooler.py", line 5, in <module>
    from .agent.agent import custom_tools
  File "/home/dukhanin/venvs/gpt-computer-assistant/lib/python3.12/site-packages/gpt_computer_assistant/agent/__init__.py", line 2, in <module>
    from .assistant import *
  File "/home/dukhanin/venvs/gpt-computer-assistant/lib/python3.12/site-packages/gpt_computer_assistant/agent/assistant.py", line 11, in <module>
    from ..screen.shot import *
  File "/home/dukhanin/venvs/gpt-computer-assistant/lib/python3.12/site-packages/gpt_computer_assistant/screen/shot.py", line 2, in <module>
    import pyautogui
  File "/home/dukhanin/venvs/gpt-computer-assistant/lib/python3.12/site-packages/pyautogui/__init__.py", line 246, in <module>
    import mouseinfo
  File "/home/dukhanin/venvs/gpt-computer-assistant/lib/python3.12/site-packages/mouseinfo/__init__.py", line 223, in <module>
    _display = Display(os.environ['DISPLAY'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dukhanin/venvs/gpt-computer-assistant/lib/python3.12/site-packages/Xlib/display.py", line 80, in __init__
    self.display = _BaseDisplay(display)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dukhanin/venvs/gpt-computer-assistant/lib/python3.12/site-packages/Xlib/display.py", line 62, in __init__
    display.Display.__init__(*(self, ) + args, **keys)
  File "/home/dukhanin/venvs/gpt-computer-assistant/lib/python3.12/site-packages/Xlib/protocol/display.py", line 129, in __init__
    raise error.DisplayConnectionError(self.display_name, r.reason)
Xlib.error.DisplayConnectionError: Can't connect to display ":0": b'Authorization required, but no authorization protocol specified\n'

OS: ubuntu 24, using venv

**Comment by Abhinavcode13** [comment]
Can you run this `sudo apt-get install xvfb` ?

**Comment by onuratakan** [comment]
Oh hi, there is an workarround for now:

```
xhost +
```

**Comment by bukhanka** [comment]
> xhost +

It wroked, thanks! got another error now.. :'-(
