### ISSUE TITLE
Bug: AttributeError when Installing on Windows

### ISSUE THREAD

**Issue by JupperTV** [Upsonic/Upsonic#168]
I can't install computerassistant through pip. This pops up after I run ```pip3 install gpt-computer-assistant``` :

```
Collecting gpt-computer-assistant
  Using cached gpt_computer_assistant-0.18.0.tar.gz (1.7 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [11 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 14, in <module>
        File "D:\Programme\Python\Lib\site-packages\setuptools\__init__.py", line 16, in <module>
          import setuptools.version
        File "D:\Programme\Python\Lib\site-packages\setuptools\version.py", line 1, in <module>
          import pkg_resources
        File "D:\Programme\Python\Lib\site-packages\pkg_resources\__init__.py", line 2191, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Python Version: 3.12.0
Windows Version: 11 23H2
Pip Version: 24.0

**Comment by onuratakan** [comment]
Ouu hi, please use newest installation method:

```console
pip3 install gpt-computer-assistant[base]
```

**Comment by JupperTV** [comment]
The same thing happens when trying to install `gpt-computer-assistant[base]`

**Comment by onuratakan** [comment]
Interesting, its must cause by your python version.

**Comment by JupperTV** [comment]
Nevermind. Turns out that I had to update setuptools...
