### ISSUE TITLE
PortAudio library not found

### ISSUE THREAD

**Issue by olives-2** [Upsonic/Upsonic#22]
When launching `computerassistant`, I get this error : 

```sh
Traceback (most recent call last):
  File "/home/molives/.local/bin/computerassistant", line 8, in <module>
    sys.exit(start())
  File "/home/molives/.local/lib/python3.10/site-packages/gpt_computer_assistant/start.py", line 19, in start
    from .gpt_computer_assistant import QApplication, MainWindow, sys
  File "/home/molives/.local/lib/python3.10/site-packages/gpt_computer_assistant/gpt_computer_assistant.py", line 8, in <module>
    from .gui.button import *
  File "/home/molives/.local/lib/python3.10/site-packages/gpt_computer_assistant/gui/button.py", line 4, in <module>
    from ..audio.record import *
  File "/home/molives/.local/lib/python3.10/site-packages/gpt_computer_assistant/audio/__init__.py", line 1, in <module>
    from .record import *
  File "/home/molives/.local/lib/python3.10/site-packages/gpt_computer_assistant/audio/record.py", line 4, in <module>
    import sounddevice as sd
  File "/home/molives/.local/lib/python3.10/site-packages/sounddevice.py", line 71, in <module>
    raise OSError('PortAudio library not found')
OSError: PortAudio library not found
```

I fixed it by installing the `libportaudio2` package in Ubuntu 22.04.
I think it would be a good idea to either install it from pip (I don't even know if this is possible) or to list it as a necessary package for Ubuntu.

**Comment by ChoksiJay** [comment]
The error message you are encountering indicates that the **sounddevice** module cannot find the **PortAudio** library, which it relies on for audio input/output operations. To resolve this issue, you need to install the **PortAudio** library and ensure that your system can access it.

Here are the steps to install **PortAudio** on different operating systems: 

**Ubuntu/Debian:**

1. Update the package list:

- `sudo apt update`

2. Install the PortAudio library and development files:

- `sudo apt install portaudio19-dev`

3. Install sounddevice Python package:

- `pip install sounddevice`

 **Fedora**

1. Install the PortAudio library and development files:

- `sudo dnf install portaudio-devel`

2. Install sounddevice Python package:

- `pip install sounddevice`

 **macOS**

1. Install PortAudio using Homebrew:

> If you don't have Homebrew installed, follow the instructions on [Homebrew's website](https://brew.sh/) to install it.

- `brew install portaudio`

2. Install sounddevice Python package:

- `pip install sounddevice`

**Windows**

1. Install PortAudio

> Download and install the PortAudio library from the official website: PortAudio..
> Alternatively, you can use a package manager like choco (Chocolatey) to install PortAudio if it's available.

2. Install sounddevice Python package:

- `pip install sounddevice`

**Comment by olives-2** [comment]
Thank you, but I said I solved my problem by installing the mentioned apt package. However, I just noticed the `sounddevice` dependency is already listed in the `requirements.txt` file, but having this dependency installed didn't do anything. I *had* to install the .deb package from the Ubuntu repositories. We should ~~either find a way to make PortAudio work from the pip dependency, or~~ explicitly indicate in the documentation that the lib needs to be installed from the repositories for Ubuntu (maybe other distros as well, I didn't try it)

**Comment by steve3p0** [comment]
I followed the above steps and I'm still getting the same errors.

**Comment by taellinglin** [comment]
I am on windows and I get this error when I try running my game which uses sounddevice and pyaudio I think:
Traceback (most recent call last):
  File "sounddevice", line 71, in <module>
OSError: PortAudio library not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "__main__", line 5, in <module>
  File "importlib._bootstrap", line 1027, in _find_and_load
  File "importlib._bootstrap", line 1006, in _find_and_load_unlocked
  File "importlib._bootstrap", line 688, in _load_unlocked
  File "importlib._bootstrap", line 856, in exec_module
  File "screenrec", line 5, in <module>
  File "importlib._bootstrap", line 1027, in _find_and_load
  File "importlib._bootstrap", line 1006, in _find_and_load_unlocked
  File "importlib._bootstrap", line 688, in _load_unlocked
  File "importlib._bootstrap", line 856, in exec_module
  File "sounddevice", line 85, in <module>
StopIteration


I am using build_apps with panda3d and I have a portaudio_x64.dll but I'm not sure where to put it.

**Comment by Bartupso** [comment]
Sorry for the late reply. We will have a new version soon
