### ISSUE TITLE
error when startup on MAC pro

### ISSUE THREAD

**Issue by taozhiyuai** [Upsonic/Upsonic#221]
`taozhiyu@Mac ~ % computerassistant
Profile: None
Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/bin/computerassistant", line 8, in <module>
    sys.exit(start())
             ^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/gpt_computer_assistant/start.py", line 88, in start
    preload_tts_microsoft_local()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/gpt_computer_assistant/audio/tts_providers/microsoft_local.py", line 35, in preload_tts_microsoft_local
    embeddings_dataset()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/gpt_computer_assistant/audio/tts_providers/microsoft_local.py", line 19, in embeddings_dataset
    embeddings_dataset_ = load_dataset("Matthijs/cmu-arctic-xvectors", split="validation")
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/datasets/load.py", line 2556, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/datasets/load.py", line 2228, in load_dataset_builder
    dataset_module = dataset_module_factory(
                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/datasets/load.py", line 1879, in dataset_module_factory
    raise e1 from None
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/datasets/load.py", line 1831, in dataset_module_factory
    can_load_config_from_parquet_export = "DEFAULT_CONFIG_NAME" not in f.read()
                                                                       ^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte`

**Comment by taozhiyuai** [comment]
`taozhiyu@Mac ~ % computerassistant --profile personal
Profile: personal
Setting profile to personal
Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/bin/computerassistant", line 8, in <module>
    sys.exit(start())
             ^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/gpt_computer_assistant/start.py", line 88, in start
    preload_tts_microsoft_local()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/gpt_computer_assistant/audio/tts_providers/microsoft_local.py", line 35, in preload_tts_microsoft_local
    embeddings_dataset()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/gpt_computer_assistant/audio/tts_providers/microsoft_local.py", line 19, in embeddings_dataset
    embeddings_dataset_ = load_dataset("Matthijs/cmu-arctic-xvectors", split="validation")
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/datasets/load.py", line 2556, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/datasets/load.py", line 2228, in load_dataset_builder
    dataset_module = dataset_module_factory(
                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/datasets/load.py", line 1879, in dataset_module_factory
    raise e1 from None
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/datasets/load.py", line 1831, in dataset_module_factory
    can_load_config_from_parquet_export = "DEFAULT_CONFIG_NAME" not in f.read()
                                                                       ^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte`

**Comment by taozhiyuai** [comment]
fail to launch from command line. but I can start from app what I install on my MAC Pro
