### ISSUE TITLE
Error while sending voice or text message.

### ISSUE THREAD

**Issue by Boguslaw-D** [Upsonic/Upsonic#235]
```
Profile: None
pygame 2.5.2 (SDL 2.28.3, Python 3.12.3)
Hello from the pygame community. https://www.pygame.org/contribute.html
Imported all libraries
API Enabled: False
Loading font
C:\Users\bogdan\AI\github\gpt-computer-assistant\gpt_computer_assistant\utils\media\SF-Pro-Text-Bold.otf
QWidget::setLayout: Attempting to set QLayout "" on MainWindow "", which already has a layout
300 210
QCssParser::parseColorValue: Specified color without alpha value but alpha given: 'rgb 0,0,0,0'
Updating from thread System: Click again when recording is done
State updated: talking
Recording started...
Recording stopped
Failed to export batch code: 400, reason: ok
Audio saved as voice_input.wav
ON RECORDING STOPPED
State updated: thinking
Updating from thread System: Thinking...
State updated: thinking
Updating from thread System: Thinking...
Previously AI response None end prev
Input Box AI
Updating from thread System: Transciption Completed. Running AI...
LLM INPUT (screenshot) Раз, два, хэллоу, хэллоу.
CHAT [{'type': 'system', 'content': {'type': 'text', 'text': 'Hi, you are an platform for vertical AI. You need to understant the user aspect and then trying to do these things and give valuation.'}, 'timestamp': 1734728687.8346045, 'that_was_empty': False}, {'type': 'human', 'content': {'type': 'text', 'text': 'អ឵កោដ់បើយថាខេដៈើយដាំកងដបាញងង្ត់ំ៘.'}, 'timestamp': 1734728687.8406892, 'auto_delete': None, 'that_was_empty': False}, {'type': 'human', 'content': {'type': 'text', 'text': "I just take a screenshot. for you to remember. Just say 'Ok.' if the user doesnt want anything before."}, 'timestamp': 1734728792.874268, 'auto_delete': None, 'that_was_empty': False}, {'type': 'human', 'content': {'type': 'image_url', 'image_url': {'url': 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAABQAAAAMgCAIAAADz+lisAAEAAElEQVR4nOy9d2AkSXk3/DxV1T15lPNKWu2uNuccby/nwIHPOYMxYIwxmNeRzwln8xqwsTHGGRsb+4W7g4PLe3ubc15JG7RKqzhKk6e7q57vj54ZjaSRdqSVdrWHfnDamZ7u6spVv3oScn+ltCwEQMaICGYXCISz/IrbBeJczyEAEMIMNRUCTKe8k9USKbBi9k3jfhqX62nX9mx31UlxG53k1g+OL9ks9smcEp65YTt7YytLFc3Yy3DGkso1HXsqttt95t6e7UXTSvtemCMht9rOcR7J5ba5VSk5LuY5TdIzNdna70qlRtlrdVZmdvtd6aGUfDXNYKOlSzXz+c+yIuTUH9UMvGlmQRN+mZFMZO5g7clz5Ir9790do+Pfftu9JV3A8ZuEmdvPTykdAuFiwGbo1TOM2ec4t41pDNtZxvjZZnw1znlilwJRmupyIcTdzs485jHnMWaw3ytD/c4il530POYxjzmFOzpIKfPjHJgd5mfy9y5G7dHnQF/7gcJMnizNYx6zhnkCPI9Zwz1KgCbK9Z2a0e8JHYTxuEdbezxmVeKaax5SfWBmM5ONddw6/XuzP84sfoCqYPzp/ix1QiK683PdnCDe8wAYqw9wZzCd+W82cdvHxnNzt0AIQHNx0hyrFzCPH2zME+B53BozO8liatrH5H9AADSXNyap0s/+YjMHl4zpI8viPntJv+cwF3j4PFKYQW3qO4SsQ+QHfOOXucjY42suLztpzE8EOQIRM1WC53nOPOYxj0kwT4DncSeQXsIJQBGApFE2OTYnzjAcuZsL17jtxizyXiLKlPalL87Nc93JgcntpJ11mksHwJkmtaMuA7JUF ............
...............QDLJ3Y5B6AOjchSpU3Z3SqUZrfc4AHARc2ATzjtYm/u3A0iu8oUHJIEIlDEO7rjAThUBGIIwiAqazGfHFoyNABBQCFBuR+w0bJy5sWhYu7DJmMPsGoFC5zvIQLM2g15NZ9weTT0Ibj8MRTLId5ZQ/avsCNh9MT8RXhlL8gzcmEeSUxctg8jYFtu8P5UHUscptufPAQmdoKiBJP8PIOV0AR+WrwQk/xp/ar5Q7QGpU0Z6JSB1UCS3VlMokl+3n/2h+jZT9/IOoPA/dPdn+0LsNEa4u3UMoGN9fCD5UsGugZTfCzdr9iiwBRJZIGVGW3iFlw8knyK5lYGMx+WG7QNJwBRF0S23W8TcOQTo+NB97s+5Yx3Zs/Ro6pC/XrDtbgoAQgRuSD6S2KaMdqDQ3z/Q6gR1QsTthL+RbLLswMeKG5WfgePEdLYqk6+Bm8kyMLMipcOX/MVxT+wwL1n+QSg6IrYMd0RvPYUQ2o/vL68Pbn9fp55SH6YwRa/2Lu48AJCnUIgGau4Rnnz//zeQ/MHr631lWAiRBxL+WyD5gqORbp2WSFkClRG42eoAVjbKlBwtS4PxsSBzVrzEA5L284EQKEwzGG9lOAvNza0NIqtOIAlhyqvauWTr1gF7AyRpgJQDnNHZ/w8gsUfv/J+Zfc8BKWPhBiGiA0j4CkDCfwMkdwCnAkmjdwqQ/Lg4K8FMIdxOs7JP1HZobRME7VEHsNYWcOJ7Dkj2oW4Pc8zb0Yr80+043ewyIGWyBTsOqqMiAXR2JynWbYf0mDspEgB48UvsT1X3zGU2+RfewuY3PRvhFCCRpUjQ8bKqVAYkrYQ7vBEbWTZPytieKV/QASbT0IWnUCTg7JD6QHLY9oDEU4CUZeF6grJPkcj7PJPWHcDYei/Bx0MGJHSUStrAZUTU3I0ta0NjCyBXgTZvDLKGBgbwDs5UIEG+aghbsze4CpSUB5Ln0ABztE2qC9qXO8X6PgZI7L8AbGEeCyRnFEAAk2ziHwd7PDLN3wMSCsiiwwBcBTUfSKiUcohzE/GA1KECcX4AOaHTh7q/jz6Q7HHLoIKIQkgXTMta/4EOipSBTa+Ppd9GQ4UcBctlnTBn0oMdBjulxRxVFFOApJ/FxKSDVLO9y86yHr+/bj6QMmJlH5RbK0cf3FDB6LYdQGKHoH9DkbxZmnXQv3UFLHjXFCkDEoNnLZ4iIzmMmJ+QhV3GerK6ersAUqbq7xJIedampbisr6HbDgck4VKrjM2AlCZSZnVIMSkjRBI52IMnI+n1AbbWE1+oM8O1FA90l+zs5cu3zDm8aTHJ3T+jIcTK1rBwv3V3YJ+SQLb++lpHGH2KtEsg+TKDAxLmgQRWDHgFILkX/b8Akk/bMdPzMyD5APaf7gEp58LtAJL7F/OE9xWANJUidQDJrIPPy9wmTh2AP+AOrapjTzvOqY8Qd9tdAgktW9klkPy9yLO2XQHJO8g+ftwfHWu1S4rUsaQdQPIXCgD+HxayVWmm/hoHAAAAAElFTkSuQmCC'}}], 'timestamp': 1734730145.0786774, 'that_was_empty': False}, {'type': 'human', 'content': {'type': 'text', 'text': 'hello'}, 'timestamp': 1734730160.1297548, 'auto_delete': None, 'that_was_empty': False}]
1734730161.6940494 1734728792.8873518 10
1734730161.6940494 1734728808.3716953 10
1734730161.6940494 1734728848.2242007 10
1734730161.6940494 1734730138.8719416 10
1734730161.6940494 1734730142.8004115 10
The model: gpt-3.5-turbo


This is file_system_tool


Error in process_text [WinError 2] The specified file cannot be found.
Traceback (most recent call last):
  File "C:\Users\boguslaw\AI\github\gpt-computer-assistant\gpt_computer_assistant\agent\process.py", line 261, in process_text
    llm_output = assistant(
                 ^^^^^^^^^^
  File "C:\Users\boguslaw\AI\github\gpt-computer-assistant\gpt_computer_assistant\agent\assistant.py", line 204, in assistant
    msg = get_agent_executor().invoke(
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\boguslaw\AI\github\gpt-computer-assistant\gpt_computer_assistant\agent\agent.py", line 80, in get_agent_executor
    tools += [mouse_scroll, click_to_text, click_to_icon, click_to_area, screenshot] + mcp_tools() + get_standard_tools()
                                                                                       ^^^^^^^^^^^
  File "C:\Users\boguslaw\AI\github\gpt-computer-assistant\gpt_computer_assistant\mcp\tool.py", line 301, in mcp_tools
    the_tools_ = file_system_tool()
                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\boguslaw\AI\github\gpt-computer-assistant\gpt_computer_assistant\mcp\tool.py", line 139, in file_system_tool
    manager.start()
  File "C:\Users\boguslaw\AI\github\gpt-computer-assistant\gpt_computer_assistant\mcp\tool.py", line 112, in start
    self.loop.run_until_complete(self._task)
  File "C:\Users\boguslaw\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\boguslaw\AI\github\gpt-computer-assistant\gpt_computer_assistant\mcp\tool.py", line 88, in _start_async
    self.client = await self.client_ctx.__aenter__()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\boguslaw\AppData\Local\Programs\Python\Python312\Lib\contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\boguslaw\AI\github\gpt-computer-assistant\GCA\Lib\site-packages\mcp\client\stdio.py", line 84, in stdio_client
    process = await anyio.open_process(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\boguslaw\AI\github\gpt-computer-assistant\GCA\Lib\site-packages\anyio\_core\_subprocesses.py", line 184, in open_process
    return await get_async_backend().open_process(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\boguslaw\AI\github\gpt-computer-assistant\GCA\Lib\site-packages\anyio\_backends\_asyncio.py", line 2596, in open_process
    process = await asyncio.create_subprocess_exec(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\boguslaw\AppData\Local\Programs\Python\Python312\Lib\asyncio\subprocess.py", line 224, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\boguslaw\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1744, in subprocess_exec
    transport = await self._make_subprocess_transport(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\boguslaw\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 400, in _make_subprocess_transport
    transp = _WindowsSubprocessTransport(self, protocol, args, shell,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\boguslaw\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "C:\Users\boguslaw\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 878, in _start
    self._proc = windows_utils.Popen(
                 ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\boguslaw\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_utils.py", line 153, in __init__
    super().__init__(args, stdin=stdin_rfd, stdout=stdout_wfd,
  File "C:\Users\boguslaw\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\boguslaw\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] Nie można odnaleźć określonego pliku
Updating from thread System: EXCEPTION: Traceback (most recent call last):
  File "C:\Users\boguslaw\AI\github\gpt-computer-assistant\gpt_computer_assistant\agent\process.py", line 261, in process_text
    llm_output = assistant(
                 ^^^^^^^^^^
  File "C:\Users\boguslaw\AI\github\gpt-computer-assistant\gpt_computer_assistant\agent\assistant.py", line 204, in assistant
    msg = get_agent_executor().invoke(
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\boguslaw\AI\github\gpt-computer-assistant\gpt_computer_assistant\agent\agent.py", line 80, in get_agent_executor
    tools += [mouse_scroll, click_to_text, click_to_icon, click_to_area, screenshot] + mcp_tools() + get_standard_tools()
                                                                                       ^^^^^^^^^^^
  File "C:\Users\boguslaw\AI\github\gpt-computer-assistant\gpt_computer_assistant\mcp\tool.py", line 301, in mcp_tools
    the_tools_ = file_system_tool()
                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\boguslaw\AI\github\gpt-computer-assistant\gpt_computer_assistant\mcp\tool.py", line 139, in file_system_tool
    manager.start()
  File "C:\Users\boguslaw\AI\github\gpt-computer-assistant\gpt_computer_assistant\mcp\tool.py", line 112, in start
    self.loop.run_until_complete(self._task)
  File "C:\Users\boguslaw\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\boguslaw\AI\github\gpt-computer-assistant\gpt_computer_assistant\mcp\tool.py", line 88, in _start_async
    self.client = await self.client_ctx.__aenter__()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\boguslaw\AppData\Local\Programs\Python\Python312\Lib\contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\boguslaw\AI\github\gpt-computer-assistant\GCA\Lib\site-packages\mcp\client\stdio.py", line 84, in stdio_client
    process = await anyio.open_process(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\boguslaw\AI\github\gpt-computer-assistant\GCA\Lib\site-packages\anyio\_core\_subprocesses.py", line 184, in open_process
    return await get_async_backend().open_process(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\boguslaw\AI\github\gpt-computer-assistant\GCA\Lib\site-packages\anyio\_backends\_asyncio.py", line 2596, in open_process
    process = await asyncio.create_subprocess_exec(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\boguslaw\AppData\Local\Programs\Python\Python312\Lib\asyncio\subprocess.py", line 224, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\boguslaw\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1744, in subprocess_exec
    transport = await self._make_subprocess_transport(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\boguslaw\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 400, in _make_subprocess_transport
    transp = _WindowsSubprocessTransport(self, protocol, args, shell,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\boguslaw\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "C:\Users\boguslaw\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 878, in _start
    self._proc = windows_utils.Popen(
                 ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\boguslaw\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_utils.py", line 153, in __init__
    super().__init__(args, stdin=stdin_rfd, stdout=stdout_wfd,
  File "C:\Users\boguslaw\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\boguslaw\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The specified file cannot be found

Failed to export batch code: 400, reason: ok
```

**Comment by IremOztimur** [comment]
Hello, thanks for opening this. Since Upsonic went through multiple transitions (GCA to early Upsonic to current version), many older issues and PRs are no longer relevant to the current architecture.

We’ve recently shipped major updates and refactors, so I’m closing this for now.

Please feel free to try the latest version here:
https://github.com/Upsonic/Upsonic

If the problem still exists or you have new feedback, please feel free to open a fresh issue.
