### ISSUE TITLE
Ollama not working?

### ISSUE THREAD

**Issue by AndyZocker** [Upsonic/Upsonic#237]
I have Ollama running, loaded Ollama 3.1 model and if i input a text prompt i get this error inside the text bar:

System: EXCEPTION: Traceback (most recent call last):
  File "C:\Users\Andy\AppData\Roaming\Python\Python312\site-packages\gpt_computer_assistant\agent\process.py", line 261, in process_text
    llm_output = assistant(
                 ^^^^^^^^^^
  File "C:\Users\Andy\AppData\Roaming\Python\Python312\site-packages\gpt_computer_assistant\agent\assistant.py", line 212, in assistant
    the_last_messages = msg["messages"]
                        ^^^
UnboundLocalError: cannot access local variable 'msg' where it is not associated with a value

**Comment by onuratakan** [comment]
Hi, we are working on a new concept for GCA. Ollama is not connected at the moment, but we will integrate it very soon. Apologies for any misinformation.

**Comment by IremOztimur** [comment]
Hello, thanks for opening this. Since Upsonic went through multiple transitions (GCA to early Upsonic to current version), many older issues and PRs are no longer relevant to the current architecture.

We’ve recently shipped major updates and refactors, so I’m closing this for now.

Please feel free to try the latest version here:
https://github.com/Upsonic/Upsonic

If the problem still exists or you have new feedback, please feel free to open a fresh issue.
