### ISSUE TITLE
Bug: OSError: ctypes.util.find_library() did not manage to locate a library called 'ole32'

### ISSUE THREAD

**Issue by sans-script** [Upsonic/Upsonic#62]
Hi!

After running  `computerassistant`, I faced this error rigth here at the end of the logs:

```powershell
Requirement already satisfied: pycparser in c:\users\sans\appdata\local\programs\python\python312\lib\site-packages (from cffi>=1.12.0->curl-cffi>=0.6.2->duckduckgo-search==5.3.0) (2.22)
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Sans\AppData\Local\Programs\Python\Python312\Scripts\computerassistant.exe\__main__.py", line 7, in <module>
  File "C:\Users\Sans\AppData\Local\Programs\Python\Python312\Lib\site-packages\gpt_computer_assistant\start.py", line 19, in start
    from .gpt_computer_assistant import QApplication, MainWindow, sys
  File "C:\Users\Sans\AppData\Local\Programs\Python\Python312\Lib\site-packages\gpt_computer_assistant\gpt_computer_assistant.py", line 9, in <module>
    from .gui.button import *
  File "C:\Users\Sans\AppData\Local\Programs\Python\Python312\Lib\site-packages\gpt_computer_assistant\gui\button.py", line 5, in <module>
    from ..audio.record import *
  File "C:\Users\Sans\AppData\Local\Programs\Python\Python312\Lib\site-packages\gpt_computer_assistant\audio\__init__.py", line 1, in <module>
    from .record import *
  File "C:\Users\Sans\AppData\Local\Programs\Python\Python312\Lib\site-packages\gpt_computer_assistant\audio\record.py", line 15, in <module>
    import soundcard as sc
  File "C:\Users\Sans\AppData\Local\Programs\Python\Python312\Lib\site-packages\soundcard\__init__.py", line 13, in <module>
    from soundcard.mediafoundation import *
  File "C:\Users\Sans\AppData\Local\Programs\Python\Python312\Lib\site-packages\soundcard\mediafoundation.py", line 19, in <module>
    _ole32 = _ffi.dlopen('ole32')
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sans\AppData\Local\Programs\Python\Python312\Lib\site-packages\cffi\api.py", line 150, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sans\AppData\Local\Programs\Python\Python312\Lib\site-packages\cffi\api.py", line 832, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sans\AppData\Local\Programs\Python\Python312\Lib\site-packages\cffi\api.py", line 827, in _load_backend_lib
    raise OSError(msg)
OSError: ctypes.util.find_library() did not manage to locate a library called 'ole32'
PS C:\Users\Sans>
```
How to fix that error? Do I miss something else?

**Comment by onuratakan** [comment]
Hmm. okay i will make a deep search. Thanks

**Comment by sans-script** [comment]
Aight, happy to help

**Comment by mymggithub** [comment]
I am also getting an issue with util when installing
ModuleNotFoundError: No module named 'utils'
and after pip install utils
i get this
ModuleNotFoundError: No module named 'utils.db'

and i am on Python 3.12.3

**Comment by Ethreal-nick** [comment]
> I am also getting an issue with util when installing ModuleNotFoundError: No module named 'utils' and after pip install utils i get this ModuleNotFoundError: No module named 'utils.db'
> 
> and i am on Python 3.12.3

Did you solve it?  I met the similar problem as yours
