### ISSUE TITLE
error running after clean  install

### ISSUE THREAD

**Issue by svankirk** [Upsonic/Upsonic#91]
After insurng a clean install with the latest python 3.12.4, I cannot run computerassistant.  I get the following error stack.  I have gone through all the dependencies as well as I am able, but haven't found anything obvious.  Any idea what might be wrong?

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "M:\Software\python\Scripts\computerassistant.exe\__main__.py", line 4, in <module>
  File "M:\Software\python\Lib\site-packages\gpt_computer_assistant\__init__.py", line 5, in <module>
    from .tooler import Tool
  File "M:\Software\python\Lib\site-packages\gpt_computer_assistant\tooler.py", line 2, in <module>
    from langchain.tools import tool
  File "M:\Software\python\Lib\site-packages\langchain\tools\__init__.py", line 23, in <module>
    from langchain_core.tools import BaseTool, StructuredTool, Tool, tool
  File "M:\Software\python\Lib\site-packages\langchain_core\tools.py", line 34, in <module>
    from langchain_core.callbacks import (
  File "M:\Software\python\Lib\site-packages\langchain_core\callbacks\__init__.py", line 22, in <module>
    from langchain_core.callbacks.manager import (
  File "M:\Software\python\Lib\site-packages\langchain_core\callbacks\manager.py", line 29, in <module>
    from langsmith.run_helpers import get_run_tree_context
  File "M:\Software\python\Lib\site-packages\langsmith\run_helpers.py", line 40, in <module>
    from langsmith import client as ls_client
  File "M:\Software\python\Lib\site-packages\langsmith\client.py", line 52, in <module>
    from langsmith import env as ls_env
  File "M:\Software\python\Lib\site-packages\langsmith\env\__init__.py", line 3, in <module>
    from langsmith.env._runtime_env import (
  File "M:\Software\python\Lib\site-packages\langsmith\env\_runtime_env.py", line 10, in <module>
    from langsmith.utils import get_docker_compose_command
  File "M:\Software\python\Lib\site-packages\langsmith\utils.py", line 31, in <module>
    from langsmith import schemas as ls_schemas
  File "M:\Software\python\Lib\site-packages\langsmith\schemas.py", line 69, in <module>
    class Example(ExampleBase):
  File "M:\Software\python\Lib\site-packages\pydantic\v1\main.py", line 286, in __new__
    cls.__try_update_forward_refs__()
  File "M:\Software\python\Lib\site-packages\pydantic\v1\main.py", line 807, in __try_update_forward_refs__
    update_model_forward_refs(cls, cls.__fields__.values(), cls.__config__.json_encoders, localns, (NameError,))
  File "M:\Software\python\Lib\site-packages\pydantic\v1\typing.py", line 554, in update_model_forward_refs
    update_field_forward_refs(f, globalns=globalns, localns=localns)
  File "M:\Software\python\Lib\site-packages\pydantic\v1\typing.py", line 520, in update_field_forward_refs
    field.type_ = evaluate_forwardref(field.type_, globalns, localns or None)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\Software\python\Lib\site-packages\pydantic\v1\typing.py", line 66, in evaluate_forwardref
    return cast(Any, type_)._evaluate(globalns, localns, set())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'

**Comment by kakakagan110** [comment]
سلام ..انگلیسی م ضعیفه بزن تو گوگل ترنلسیت ترجمه کنه برات 

ار ورژن 3.12.3 استفاده کنی این ارور رو نمیده ..تست کن شاید مشکلت حل شد

**Comment by svankirk** [comment]
Thank you!  I will give it a try.

**Comment by horace-yip** [comment]
Using Python 3.12.3 resolved the problem for me. Thank you.
